### ISSUE TITLE
Issue with buildStepsDb.pl Script - Warnings and Failed Fetch

### ISSUE THREAD

**Issue by SnowPeak7** [morgannprice/PaperBLAST#13]
I encountered multiple warnings and a fetch failure while running the buildStepsDb.pl script. The process was aimed at building a query file, but it seems to have run into issues with specific IDs and a failed attempt to fetch data from UniProt.

For test, I created a folder named ss under the gaps folder and subsequently copied the files from the aa folder.Then I run the commadn below.

Command: `bin/buildStepsDb.pl -set ss -doquery`

ERRO:
```
Building query file for arg
Warning: No curated id matches the ignore BRENDA::Q8P8J7 for step argB
Warning: lysJ	[LysW]-2-aminoadipate semialdehyde transaminase / [LysW]-glutamate semialdehyde transaminase: no curated hits for [LysW]-aminoadipate semialdehyde/glutamate semialdehyde transaminase
Warning: lysY	[LysW]-2-aminoadipate 6-phosphate reductase / [LysW]-glutamylphosphate reductase: no curated hits for [LysW]-L-2-aminoadipate/[LysW]-L-glutamate phosphate reductase
Warning: TIGR03246 (succinylornithine transaminase family) is of type subfamily
Wrote /data1/bioinfo_software/PaperBLAST/bin/../tmp/path.ss/arg.query
Building query file for asn
Warning: gatA	aspartyl/glutamyl-tRNA(Asn/Gln) amidotransferase subunit A: no curated hits for aspartyl/glutamyl-tRNA(Asn/Gln) amidotransferase subunit A
Warning: gatC	aspartyl/glutamyl-tRNA(Asn/Gln) amidotransferase subunit C: no curated hits for aspartyl/glutamyl-tRNA(Asn/Gln) amidotransferase subunit C
Failed to fetch https://www.uniprot.org/uniprot/I7EPB8.txt
gapquery.pl failed for asn:  at bin/buildStepsDb.pl line 52.

**Comment by morgannprice** [comment]
The warnings are harmless,. The failure to fetch I7EPB8 is because it is no longer a valid UniProt id.

https://www.uniprot.org/uniprotkb/I7EPB8/history

Unfortunately, a number of the uniprot ids in the original GapMind rules have been deleted. If you want to keep testing your curated db, you can just remove the uniprot ids from the rules. I'm in the process of updating the rules for GapMind for amino acid biosynthesis, but I don't  have anything I'm ready to release yet.

Alternatively, you can use the publicly available curated db instead of using your own.

**Comment by SnowPeak7** [comment]
Thank you for answering and providing such detailed information!
